version: 2
updates:

- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: "Europe/London"
  open-pull-requests-limit: 99
  assignees:
  - credfeto
  commit-message:
    prefix: "[Dependencies]"
  labels:
  - "python"
  - "dependencies"
  - "Changelog Not Required"
  allow:
  - dependency-type: all